name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IP: ${{ secrets.IP_VPS }}
      PORT: ${{ secrets.PORT_VPS }}
      LOGIN: ${{ secrets.LOGIN_VPS }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.IP }}
          username: ${{ env.LOGIN }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ env.PORT }}
          script: |
            # Installer Node.js et PM2 (garantit accessibilité dans SSH non interactif)
            apt-get update
            curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
            apt-get install -y nodejs
            npm install -g pm2
            # Créer le dossier s'il n'existe pas
            mkdir -p ~/rapverse

            # Cloner le dépôt si ce n'est pas déjà un repo Git
            if [ ! -d ~/rapverse/.git ]; then
              git clone https://github.com/${{ github.repository }} ~/rapverse
            fi

            cd ~/rapverse
            git pull origin master


            # Créer ou écraser le fichier .env avec les valeurs secrètes
            cat > .env <<EOF
            NODE_ENV=production
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            EOF

            docker compose up -d

            # Installer les dépendances
            npm install

            # Générer les classes Prisma
            npx prisma generate

            # Appliquer les migrations (prod safe)
            npx prisma migrate deploy

            npm run build

            pm2 restart rapverse || pm2 start npm --name "rapverse" -- start
